### ISSUE TITLE
Phinch v1 Portal still available?

### ISSUE THREAD

**Issue by geboro** [PhinchApp/Phinch#8]
It's great there is a standalone version for Phinch!
But we are at the middle of a course right now... is the portal for Phinch1 still available?
Cheers!

**Comment by hollybik** [comment]
The Phinch1 web portal has been officially decommissioned as of May 10th, due to an outdated code base and lack of support for newer BIOM 2.0 files. The new Phinch app should work in exactly the same way, with many of the previous features/tools consolidated into a single visualization window. The new app is compatible with Mac OS X, Windows, and Linux operating systems - just choose the correct download for your computer.

Please let us know if you have any issues transitioning to the new Phinch2 desktop app!
