### ISSUE TITLE
Only Stacked bargraph?STACKED BARGRAPH 

### ISSUE THREAD

**Issue by javiercnav** [PhinchApp/Phinch#9]
Hi, I love Phinch, congrats on the awesome V2. I have a question, do you only have a single type of visualization option as of now? STACKED BARGRAPH?
Thanks!

**Comment by BSC3402L** [comment]
same here, I have only stacked bar? any suggestions

**Comment by hollybik** [comment]
Thanks for downloading the new Phinch desktop app! Since we had to completely refactor the codebase from the original phinch.org web server, we had to streamline the visualization window for this first initial release. The previous Donuts Charts and Attributes Column Chart windows have been incorporated into the main taxonomy bar chart window - other visualizations (Sankey diagram, Bubble charts) may be re-implemented in the next few months now that we have a stable app release.

Are there any visuals from the old Phinch which you found particularly useful? Any feedback would be much appreciated, and we will use this as we develop new visualization features.

**Comment by vebaev** [comment]
Is there a way of accessing the old Phinch online?

**Comment by Najayo** [comment]
Hi there! I love phinch bubble and donuts charts. Is there any way to create them right now, while they are being implemented in the new app? there are also other online online tools to create the bar charts so in my opinion, other kind of charts is what makes phinch different.
